# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audio.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61udio.proto\x12\x05\x61udio\"\x1a\n\nAudioChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"&\n\x13StreamAudioResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2N\n\x0c\x41udioService\x12>\n\x0bStreamAudio\x12\x11.audio.AudioChunk\x1a\x1a.audio.StreamAudioResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_AUDIOCHUNK']._serialized_start=22
  _globals['_AUDIOCHUNK']._serialized_end=48
  _globals['_STREAMAUDIORESPONSE']._serialized_start=50
  _globals['_STREAMAUDIORESPONSE']._serialized_end=88
  _globals['_AUDIOSERVICE']._serialized_start=90
  _globals['_AUDIOSERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
